In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# UEFA club European Cup Web Scraping

In this notebook, we will develop and review a web scraper to extract all matches played in the major European Club Cup tournments from 1980 onward. The goal is to create a dataset with the following information:

- `season`
- `competition`
- `round`
- `team_a`,
- `country_a`,
- `team_b`,
- `country_b`
- `score_leg1`
- `score_leg2`
- `score_aggregate`
- `extra_time`
- `penalties`

The first step of our analysis will concentrate on single results only, meaning that we will use the information stored in the first nine columns only. The idea, at least as a first insight, is to compare the winning/points ratio of all clubs by nation without giving any weight to the competition, something that can be done in a further step. 

The process to build the webscraper is iterative and is done in collaboration with Claude. The web resources that will be used as main source is well structured and yet contains different spots where the script to scrape the data must be adapted as we collect the data - *learning point*.

## Scraping data from kassiesa.net

- source: [kassiesa.net](https://kassiesa.net/uefa/index.html)

This database contains all match results and calculated coefficients of European Cup football since 1955, covering all rounds including qualifiers. It's one of the most thorough free sources and is well-regarded among football statisticians. It will be used as starting point for collecting the data. A possible exhaustive approach might be:

- Starting with Kassiesa.net as ground truth (it has all three competitions, nationalities, and correct results). Scrapeing the season-by-season match pages (they're structured HTML tables). This will give us ~1980–present across all competitions.
- Supplement with jalapic/champs CSV (free direct download) for Champions League 1980–2017 as a cross-check.
- For the extra-time / penalties distinction, ***Kassiesa.net does not always separate these from 90-min scores***. We may need to cross-reference with EuroCupsHistory (eurocupshistory.com) for knockout rounds specifically.

In [2]:
import subprocess
import sys

# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1981', '--end', '1983', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 3 seasons (1980/81 → 1982/83) …

  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches

Total: 382 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

#### Testing the scripts through the '80

In [3]:

# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1980', '--end', '1990', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 11 seasons (1979/80 → 1989/90) …

  1979/80 … 127 matches
  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches
  1983/84 … 125 matches
  1984/85 … 125 matches
  1985/86 … 123 matches
  1986/87 … 123 matches
  1987/88 … 126 matches
  1988/89 … 125 matches
  1989/90 … 127 matches

Total: 1383 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

#### Testing the scripts through the '90

In [6]:

# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1990', '--end', '2000', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 11 seasons (1989/90 → 1999/00) …

  1989/90 … 127 matches
  1990/91 … 125 matches
  1991/92 … 133 matches
  1992/93 … 139 matches
  1993/94 … 154 matches
  1994/95 … 172 matches
  1995/96 … 181 matches
  1996/97 … 203 matches
  1997/98 … 221 matches
  1998/99 … 226 matches
  1999/00 … 259 matches

Total: 1940 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

#### Testing the scripts from 2000 to 2010

In [7]:
# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2000', '--end', '2010', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 11 seasons (1999/00 → 2009/10) …

  1999/00 … 259 matches
  2000/01 … 263 matches
  2001/02 … 263 matches
  2002/03 … 263 matches
  2003/04 … 247 matches
  2004/05 … 311 matches
  2005/06 … 312 matches
  2006/07 … 321 matches
  2007/08 … 327 matches
  2008/09 … 327 matches
  2009/10 … 346 matches

Total: 3239 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

#### Testing the script from 2010 to 2020

In [8]:
# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2010', '--end', '2020', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 11 seasons (2009/10 → 2019/20) …

  2009/10 … 346 matches
  2010/11 … 348 matches
  2011/12 … 348 matches
  2012/13 … 347 matches
  2013/14 … 347 matches
  2014/15 … 350 matches
  2015/16 … 347 matches
  2016/17 … 344 matches
  2017/18 … 347 matches
  2018/19 … 370 matches
  2019/20 … 370 matches

Total: 3864 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

#### Testing the script 2020 to 2025

In [9]:
# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '2020', '--end', '2026', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 7 seasons (2019/20 → 2025/26) …

  2019/20 … 370 matches
  2020/21 … 370 matches
  2021/22 … 411 matches
  2022/23 … 405 matches
  2023/24 … 406 matches
  2024/25 … 678 matches
  2025/26 … 659 matches

Total: 3299 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

#### Testing the script 1979 to 2026

In [3]:
import subprocess
import sys

# Run the uefa_scraper.py script with default arguments
result = subprocess.run([sys.executable, '../src/uefa_scraper.py', '--start', '1979', '--end', '2026', '--output', '../data/uefa_results.csv'], capture_output=True, text=True)

# Print the output
print("STDOUT:")
print(result.stdout)
print("STDERR:")
print(result.stderr)

STDOUT:
Scraping 48 seasons (1978/79 → 2025/26) …

  1978/79 … 125 matches
  1979/80 … 127 matches
  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches
  1983/84 … 125 matches
  1984/85 … 125 matches
  1985/86 … 123 matches
  1986/87 … 123 matches
  1987/88 … 126 matches
  1988/89 … 125 matches
  1989/90 … 127 matches
  1990/91 … 125 matches
  1991/92 … 133 matches
  1992/93 … 139 matches
  1993/94 … 154 matches
  1994/95 … 172 matches
  1995/96 … 181 matches
  1996/97 … 203 matches
  1997/98 … 221 matches
  1998/99 … 226 matches
  1999/00 … 259 matches
  2000/01 … 263 matches
  2001/02 … 263 matches
  2002/03 … 263 matches
  2003/04 … 247 matches
  2004/05 … 311 matches
  2005/06 … 312 matches
  2006/07 … 321 matches
  2007/08 … 327 matches
  2008/09 … 327 matches
  2009/10 … 346 matches
  2010/11 … 348 matches
  2011/12 … 348 matches
  2012/13 … 347 matches
  2013/14 … 347 matches
  2014/15 … 350 matches
  2015/16 … 347 matches
  2016/17 … 344 matches
  2017/18 … 347 matches
  2018/19 … 370 matches
  2019/20 … 370 matches
  2020/21 … 370 matches
  2021/22 … 411 matches
  2022/23 … 405 matches
  2023/24 … 406 matches
  2024/25 … 678 matches
  2025/26 … 659 matches

Total: 12748 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:

output:
```
STDOUT:
Scraping 48 seasons (1978/79 → 2025/26) …

  1978/79 … 125 matches
  1979/80 … 127 matches
  1980/81 … 128 matches
  1981/82 … 127 matches
  1982/83 … 127 matches
  1983/84 … 125 matches
  1984/85 … 125 matches
  1985/86 … 123 matches
  1986/87 … 123 matches
  1987/88 … 126 matches
  1988/89 … 125 matches
  1989/90 … 127 matches
  1990/91 … 125 matches
  1991/92 … 133 matches
  1992/93 … 139 matches
  1993/94 … 154 matches
  1994/95 … 172 matches
  1995/96 … 181 matches
  1996/97 … 203 matches
  1997/98 … 221 matches
  1998/99 … 226 matches
  1999/00 … 259 matches
  2000/01 … 263 matches
  2001/02 … 263 matches
  2002/03 … 263 matches
  2003/04 … 247 matches
  2004/05 … 311 matches
  2005/06 … 312 matches
  2006/07 … 321 matches
  2007/08 … 327 matches
  2008/09 … 327 matches
  2009/10 … 346 matches
  2010/11 … 348 matches
  2011/12 … 348 matches
  2012/13 … 347 matches
  2013/14 … 347 matches
  2014/15 … 350 matches
  2015/16 … 347 matches
  2016/17 … 344 matches
  2017/18 … 347 matches
  2018/19 … 370 matches
  2019/20 … 370 matches
  2020/21 … 370 matches
  2021/22 … 411 matches
  2022/23 … 405 matches
  2023/24 … 406 matches
  2024/25 … 678 matches
  2025/26 … 659 matches

Total: 12748 matches
Writing → ../data/uefa_results.csv
Done ✓

STDERR:
```

In [4]:
raw_data = pd.read_csv('../data/uefa_results.csv')
raw_data.head()

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
0,1978/79,CL,Qualifying Round,AS Monaco,Fra,Steaua Bucuresti,Rom,3-0,0-2,3-2,no,no
1,1978/79,CL,Round 1,Nottingham Forest,Eng,Liverpool,Eng,2-0,0-0,2-0,no,no
2,1978/79,CL,Round 1,Juventus,Ita,Glasgow Rangers,Sco,1-0,0-2,1-2,no,no
3,1978/79,CL,Round 1,Linfield Belfast,Nir,Lillestrøm SK,Nor,0-0,0-1,0-1,no,no
4,1978/79,CL,Round 1,Real Madrid,Esp,Progrès Niederkorn,Lux,5-0,7-0,12-0,no,no

In [5]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12748 entries, 0 to 12747
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           12748 non-null  str
 1   competition      12748 non-null  str
 2   round            12748 non-null  str
 3   team_a           12748 non-null  str
 4   country_a        12748 non-null  str
 5   team_b           12748 non-null  str
 6   country_b        12748 non-null  str
 7   score_leg1       12748 non-null  str
 8   score_leg2       11196 non-null  str
 9   score_aggregate  12748 non-null  str
 10  extra_time       12748 non-null  str
 11  penalties        12748 non-null  str
dtypes: str(12)
memory usage: 1.2 MB

In [6]:
raw_data.tail()

,season,competition,round,team_a,country_a,team_b,country_b,score_leg1,score_leg2,score_aggregate,extra_time,penalties
12743,2025/26,CO,Round of 16,Fiorentina,Ita,Raków Czestochowa,Pol,2-1,NaN,2-1,no,no
12744,2025/26,CO,Round of 16,Samsunspor,Tur,Rayo Vallecano,Esp,1-3,NaN,1-3,no,no
12745,2025/26,CO,Round of 16,NK Celje,Slo,AEK Athens,Gre,0-4,NaN,0-4,no,no
12746,2025/26,CO,Round of 16,Sigma Olomouc,Cze,FSV Mainz 05,Ger,0-0,NaN,0-0,no,no
12747,2025/26,CO,Round of 16,NK Rijeka,Cro,RC Strasbourg,Fra,1-2,NaN,1-2,no,no